### PR TITLE
Set XML version to 1.0 from 1.1 in files.go for compatibility

### PR DESCRIPTION
**Pull request by brandon099**
This just updates the xml version to 1.0 from 1.1. XML 1.1 is not very widely implemented, so for compatibility it is suggested to use 1.0.

Clients that do not have 1.1 implemented throw the following error:
```
XML Parsing Error: XML declaration not well-formed
Location: http://10.0.0.5/test.xml
Line Number 1, Column 16:
<?xml version="1.1"?><!DOCTYPE _[<!ELEMENT _ EMPTY>]><_/>
```

### CODE REVIEW

**Comment by bmrzycki** [comment]
Hello @brandon099 ! Thanks for the fix. When I originally added the default files I used the contents of [mathiasbynens/small](https://github.com/mathiasbynens/small) for the different file types. I naively grabbed the latest version of top-level file types without checking if it was used or implemented. I verified locally Firefox isn't happy with what nullserv emits for XML. I think the right answer here is to use the contents of [small/xml-1.0-valid.xml](https://github.com/mathiasbynens/small/blob/master/xml-1.0-valid.xml) as the replacement (note there is no newline):
```
<!DOCTYPE _[<!ELEMENT _ EMPTY>]><_/>
```

I've tested it locally and it works well with Firefox. Would you be interested in pushing the updated change? You should get credit for the error. :) If you'd rather I push it just let me know.

Thanks again!

**Comment by brandon099** [comment]
Alright, I've updated that commit with the version from [mathiasbynens/small](https://github.com/mathiasbynens/small) -- awesome repo!

Confirmed it looks good in Firefox when running from this commit as well.

Thanks!

**Comment by bmrzycki** [comment]
Looks perfect, thanks! I'll merge it shortly. :)

Looking at [mathiasbynens/small](https://github.com/mathiasbynens/small) it seems the jpeg file has shrunk since I last looked at it and will update it.

This also brings up something else I've been musing: the modern web uses almost no http anymore in my personal statistic monitoring almost all of the redirected links go to https, with a few going to the empty url `/` or `/something.jpg`. I'm mulling pulling the files for bmp, tiff, svg and just having them become 404 messages: the web has moved on from when I originally wrote this...

**Comment by bmrzycki** [comment]
> Looking at mathiasbynens/small it seems the jpeg file has shrunk since I last looked at it and will update it.

On second glance I won't be doing this: the smaller jpeg file doesn't work as cleanly as the as the larger 1x1 pixel jpeg. Some browsers end up printing the jpeg url in the jpeg layout location making page layouts more cluttered.

**Pull request merged**
